# Generated by Django 4.2 on 2026-04-24 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timetable_app', '0002_add_unit_model_and_course_dept'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('department', 'code')},
        ),
        migrations.AlterField(
            model_name='course',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='timetable_app.program'),
        ),
    ]
